### ISSUE TITLE
PHP Fatal error: 1064:You have an error in your SQL syntax

### ISSUE THREAD

**Issue by nikhilchaudhary70** [lat9/customer_tax_exempt_2#1]
There is a small error when we have two tax defined comma separated in the Customer Tax Exempt field.

We need to change the below line of code
from:
`$this->exemptions_list = "'" . implode(", '", $exemptions) . "'";`
to:
`$this->exemptions_list = "'" . implode("', '", $exemptions) . "'";`

There is a single quote missing in implode function.

**Comment by lat9** [comment]
Nice one; thanks for the fix.  I'll get that going over the weekend.
