### ISSUE TITLE
SQL ErrorL Expression #2 of SELECT list is not in GROUP BY clause and contains nonaggregated column

### ISSUE THREAD

**Issue by matt-in-real-life** [lat9/customer_tax_exempt_2#3]
When a value other than "ALL" is specified for the exemptions for the customer, the following error is triggered:

`PHP Fatal error: 1055:Expression #2 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'tr.tax_description' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by :: SELECT SUM(tax_rate) AS tax_rate_summed, tax_description, ANY_VALUE(tax_priority)
              FROM tax_rates tr
                    LEFT JOIN zones_to_geo_zones za 
                        ON tr.tax_zone_id = za.geo_zone_id
                    LEFT JOIN geo_zones tz 
                        ON tz.geo_zone_id = tr.tax_zone_id
              WHERE tr.tax_class_id = 1
                AND tr.tax_description NOT IN ('NC TAX 6.75%')
                AND (za.zone_country_id IS NULL OR za.zone_country_id = 0 OR za.zone_country_id = 223)
                AND (za.zone_id IS NULL OR za.zone_id = 0 OR za.zone_id = 44)
              GROUP BY tr.tax_priority
              ORDER BY tr.tax_priority ==> (as called by) /***/includes/classes/observers/TaxExemptCustomerObserver.php on line 258 <== in /***/includes/classes/db/mysql/query_factory.php on line 171.`

Forgoing SQL mode changes, changing the GROUP BY on line 159 in includes/classes/observers/TaxExemptCustomerObserver.php to include **tax_description** seems to rectify.

Current:
`GROUP BY tr.tax_priority`

Amended:
`GROUP BY tr.tax_priority, tr.tax_description`

Database Engine: MySQL 5.7.39

**Comment by lat9** [comment]
As an alternative solution, the `tax_description` isn't needed by the calling method, so I'll suggest changing
`            "SELECT SUM(tax_rate) AS tax_rate_summed, tax_description, tax_priority`
to
`            "SELECT SUM(tax_rate) AS tax_rate_summed, tax_priority`
